# Generated by Django 5.1.7 on 2025-04-24 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('START', 'Start'), ('TEXT', 'Text'), ('LIST', 'List'), ('END', 'End')], max_length=50)),
                ('text', models.TextField(blank=True, null=True)),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('list_header', models.CharField(blank=True, max_length=255, null=True)),
                ('bot_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='botflow.botflow')),
                ('next_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_nodes', to='botflow.node')),
            ],
        ),
        migrations.CreateModel(
            name='ListOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_options', to='botflow.node')),
                ('target_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_nodes', to='botflow.node')),
            ],
        ),
        migrations.AddField(
            model_name='botflow',
            name='start_node',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_botflow', to='botflow.node'),
        ),
    ]
