# Generated by Django 5.1.7 on 2025-04-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
