# Generated by Django 5.1.7 on 2025-04-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botflow', '0002_alter_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
