# Generated by Django 5.1.7 on 2025-05-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("botflow", "0003_alter_node_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="file_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="node",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="node",
            name="type",
            field=models.CharField(
                choices=[
                    ("START", "Start"),
                    ("TEXT", "Text"),
                    ("IMAGE", "Image"),
                    ("FILE", "File"),
                    ("ANSWER", "Answer"),
                    ("LIST", "List"),
                    ("END", "End"),
                ],
                max_length=50,
            ),
        ),
    ]
